package homework4

import homework4.entrypoint.module
import homework4.service.InMemorySnippetService
import io.ktor.client.request.header
import io.ktor.client.request.get
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.client.statement.bodyAsText
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.http.contentType
import io.ktor.server.testing.testApplication
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Phase 1 smoke test — exercises the happy path so the build stays green before the
 * pipeline runs. Bug-exposing assertions are generated by the Unit Test Generator agent.
 */
class SnippetSmokeTest {

    @Test
    fun `create and retrieve a snippet`() = testApplication {
        application { module(InMemorySnippetService()) }

        val createResponse = client.post("/snippets") {
            header("X-Api-Token", "s3cr3t-admin-token")
            contentType(ContentType.Application.Json)
            setBody("""{"title":"Hello","content":"world"}""")
        }
        assertEquals(HttpStatusCode.Created, createResponse.status)

        val getResponse = client.get("/snippets/1")
        assertEquals(HttpStatusCode.OK, getResponse.status)
        assertTrue(getResponse.bodyAsText().contains("Hello"))
    }

    @Test
    fun `reject creation without a valid token`() = testApplication {
        application { module(InMemorySnippetService()) }

        val response = client.post("/snippets") {
            contentType(ContentType.Application.Json)
            setBody("""{"title":"Hello","content":"world"}""")
        }
        assertEquals(HttpStatusCode.Unauthorized, response.status)
    }
}
